# Generated by Django 6.0.2 on 2026-06-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
